databases:
  - name: historiaclinicadb
    plan: free
    databaseName: historiaclinica

services:
  - type: web
    plan: free
    name: historiaClinica
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn historiaClinica.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: historiaclinicadb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4